# Generated by Django 3.2.8 on 2023-05-23 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20230523_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='rating',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
