# Generated by Django 3.2.8 on 2023-05-23 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_experience_rating'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogPost',
            new_name='Blog',
        ),
    ]
